version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.12.3
    steps:
      - checkout
      - run:
          name: Validate terraform code
          command: |
            terraform init -backend=false
            terraform validate
